import {
  AgentNode,
  DetectionRule,
  Incident,
  IoCRecord,
  NormalizedLog,
  PlaybookAction,
  SecurityAlert,
  UEBAProfile,
} from './types';

export const INITIAL_AGENTS: AgentNode[] = [
  {
    id: 'AGT-001',
    hostname: 'prd-db-01.rakshak.internal',
    ip: '10.10.20.11',
    os: 'Ubuntu 24.04 LTS (Kernel 6.8)',
    osFamily: 'Linux',
    version: 'Wazuh-Rakshak v4.9.2',
    status: 'Active',
    criticality: 'Tier-0 Crown Jewel',
    riskMultiplier: 2.0,
    lastHeartbeatSec: 2,
    eps: 142,
    cpuLoad: 38,
    memUsage: 64,
    privilegedUsers: ['root', 'postgres', 'admin_akhtar'],
  },
  {
    id: 'AGT-002',
    hostname: 'dc-win-01.rakshak.internal',
    ip: '10.10.10.5',
    os: 'Windows Server 2022 Datacenter',
    osFamily: 'Windows',
    version: 'Wazuh-Rakshak v4.9.2',
    status: 'Active',
    criticality: 'Tier-0 Crown Jewel',
    riskMultiplier: 2.0,
    lastHeartbeatSec: 1,
    eps: 218,
    cpuLoad: 44,
    memUsage: 71,
    privilegedUsers: ['SYSTEM', 'Administrator', 'svc-backup'],
  },
  {
    id: 'AGT-003',
    hostname: 'auth-sso-01.rakshak.internal',
    ip: '10.10.15.20',
    os: 'Red Hat Enterprise Linux 9.4',
    osFamily: 'Linux',
    version: 'Wazuh-Rakshak v4.9.2',
    status: 'Degraded',
    criticality: 'Tier-1 Production',
    riskMultiplier: 1.5,
    lastHeartbeatSec: 9,
    eps: 310,
    cpuLoad: 79,
    memUsage: 82,
    privilegedUsers: ['root', 'admin_akhtar'],
  },
  {
    id: 'AGT-004',
    hostname: 'k8s-ingress-02.rakshak.internal',
    ip: '10.10.30.42',
    os: 'Debian GNU/Linux 12 (Bookworm)',
    osFamily: 'Linux',
    version: 'Wazuh-Rakshak v4.9.1',
    status: 'Active',
    criticality: 'Tier-1 Production',
    riskMultiplier: 1.5,
    lastHeartbeatSec: 3,
    eps: 185,
    cpuLoad: 29,
    memUsage: 51,
    privilegedUsers: ['root', 'kube-admin'],
  },
  {
    id: 'AGT-005',
    hostname: 'fin-wks-14.rakshak.internal',
    ip: '10.24.12.88',
    os: 'Windows 11 Enterprise 23H2',
    osFamily: 'Windows',
    version: 'Wazuh-Rakshak v4.9.0',
    status: 'Active',
    criticality: 'Tier-2 Standard',
    riskMultiplier: 1.0,
    lastHeartbeatSec: 4,
    eps: 34,
    cpuLoad: 18,
    memUsage: 47,
    privilegedUsers: ['m_chen', 'local_admin'],
  },
];

export const DETECTION_RULES: DetectionRule[] = [
  {
    id: 'RULE-101',
    name: 'Repeated Authentication Failures (Brute Force / Spray)',
    description: 'Detects >= 4 failed SSH (pam_unix/sshd) or Windows Logon (EventID 4625) attempts from the same source IP within a 5-minute correlation window.',
    defaultSeverity: 'High',
    baseConfidence: 86,
    mitreTactic: 'Credential Access',
    mitreTechniqueId: 'T1110.001',
    mitreTechniqueName: 'Brute Force: Password Guessing',
    mitreUrl: 'https://attack.mitre.org/techniques/T1110/001/',
    attackStage: 'Credential Access',
    wazuhRuleEquivalent: 'Wazuh Rule 5712 / 60122',
    evidenceCriteria: 'Multiple consecutive outcome=Failure events in Authentication category sharing sourceIp or target user.',
    enabled: true,
  },
  {
    id: 'RULE-102',
    name: 'Successful Login Following Multiple Failures (Credential Compromise)',
    description: 'Identifies a successful authentication (sshd Accepted / EventID 4624) immediately preceded by >= 3 failed login attempts for the same account or source IP.',
    defaultSeverity: 'Critical',
    baseConfidence: 94,
    mitreTactic: 'Initial Access',
    mitreTechniqueId: 'T1078',
    mitreTechniqueName: 'Valid Accounts',
    mitreUrl: 'https://attack.mitre.org/techniques/T1078/',
    attackStage: 'Reconnaissance & Initial Access',
    wazuhRuleEquivalent: 'Wazuh Rule 5715 + Correlation 40111',
    evidenceCriteria: 'Chronological sequence: [Failure x N] -> [Success] within 10 minutes on identical user or sourceIp.',
    enabled: true,
  },
  {
    id: 'RULE-103',
    name: 'Off-Hours or Unfamiliar Geolocation Authentication',
    description: 'Flags successful authentications occurring between 01:00–05:00 local time or originating from an ASN/country outside the entity UEBA baseline.',
    defaultSeverity: 'Medium',
    baseConfidence: 78,
    mitreTactic: 'Initial Access',
    mitreTechniqueId: 'T1078.004',
    mitreTechniqueName: 'Valid Accounts: Cloud & Remote Accounts',
    mitreUrl: 'https://attack.mitre.org/techniques/T1078/004/',
    attackStage: 'Reconnaissance & Initial Access',
    wazuhRuleEquivalent: 'Wazuh Rule 100210 (UEBA Geo/Time Anomaly)',
    evidenceCriteria: 'isUnusualGeo=true OR isUnusualHour=true on outcome=Success authentication event.',
    enabled: true,
  },
  {
    id: 'RULE-104',
    name: 'Suspicious Privilege Escalation or Admin Group Modification',
    description: 'Detects unauthorized sudo to root, su session elevation, Windows EventID 4672 (Special Privileges Assigned), or EventID 4720 (Account Created).',
    defaultSeverity: 'Critical',
    baseConfidence: 91,
    mitreTactic: 'Privilege Escalation',
    mitreTechniqueId: 'T1548.003',
    mitreTechniqueName: 'Abuse Elevation Control Mechanism: Sudo and Sudo Caching',
    mitreUrl: 'https://attack.mitre.org/techniques/T1548/003/',
    attackStage: 'Privilege Escalation',
    wazuhRuleEquivalent: 'Wazuh Rule 5402 / 60106 / 60109',
    evidenceCriteria: 'category=PrivilegeChange or AccountManagement with root/SYSTEM token assignment or sudoers modification.',
    enabled: true,
  },
  {
    id: 'RULE-105',
    name: 'Anomalous Event Frequency & Outbound Data Burst',
    description: 'Flags abnormal volume spikes or large outbound archive/database transfers deviating > 3.0 sigma from the host historical EPS/egress baseline.',
    defaultSeverity: 'High',
    baseConfidence: 84,
    mitreTactic: 'Exfiltration',
    mitreTechniqueId: 'T1048',
    mitreTechniqueName: 'Exfiltration Over Alternative Protocol',
    mitreUrl: 'https://attack.mitre.org/techniques/T1048/',
    attackStage: 'Collection & Exfiltration',
    wazuhRuleEquivalent: 'Wazuh Rule 87904 (Statistical Burst Detector)',
    evidenceCriteria: 'category=NetworkExfiltration or anomalyScore >= 82 on crown-jewel asset.',
    enabled: true,
  },
];

export const INITIAL_LOGS: NormalizedLog[] = [
  // --- ATTACK CHAIN 1: Linux SSH Brute Force -> Compromise -> Sudo Escalation -> DB Exfil ---
  {
    id: 'EVT-9001',
    timestamp: '2026-10-01T03:08:12Z',
    host: 'auth-sso-01.rakshak.internal',
    os: 'Linux',
    user: 'admin_akhtar',
    sourceIp: '185.220.101.44',
    geoCountry: 'DE (Tor Exit Node)',
    isUnusualGeo: true,
    isUnusualHour: true,
    category: 'Authentication',
    eventCode: 'sshd_failed_password',
    outcome: 'Failure',
    processName: 'sshd[19402]',
    rawLog: 'Oct  1 03:08:12 auth-sso-01 sshd[19402]: Failed password for admin_akhtar from 185.220.101.44 port 48192 ssh2',
    normalizedSummary: 'SSH password authentication failed for user admin_akhtar from Tor node 185.220.101.44 (Attempt 1/5)',
    assetCriticality: 'Tier-1 Production',
    isPrivilegedAccount: true,
    groundTruthMalicious: true,
    ruleFlagged: true,
    anomalyScore: 84,
    anomalyFlagged: true,
    matchedRuleId: 'RULE-101',
  },
  {
    id: 'EVT-9002',
    timestamp: '2026-10-01T03:08:19Z',
    host: 'auth-sso-01.rakshak.internal',
    os: 'Linux',
    user: 'admin_akhtar',
    sourceIp: '185.220.101.44',
    geoCountry: 'DE (Tor Exit Node)',
    isUnusualGeo: true,
    isUnusualHour: true,
    category: 'Authentication',
    eventCode: 'sshd_failed_password',
    outcome: 'Failure',
    processName: 'sshd[19405]',
    rawLog: 'Oct  1 03:08:19 auth-sso-01 sshd[19405]: Failed password for admin_akhtar from 185.220.101.44 port 48204 ssh2',
    normalizedSummary: 'SSH password authentication failed for user admin_akhtar from Tor node 185.220.101.44 (Attempt 2/5)',
    assetCriticality: 'Tier-1 Production',
    isPrivilegedAccount: true,
    groundTruthMalicious: true,
    ruleFlagged: true,
    anomalyScore: 86,
    anomalyFlagged: true,
    matchedRuleId: 'RULE-101',
  },
  {
    id: 'EVT-9003',
    timestamp: '2026-10-01T03:08:27Z',
    host: 'auth-sso-01.rakshak.internal',
    os: 'Linux',
    user: 'admin_akhtar',
    sourceIp: '185.220.101.44',
    geoCountry: 'DE (Tor Exit Node)',
    isUnusualGeo: true,
    isUnusualHour: true,
    category: 'Authentication',
    eventCode: 'sshd_failed_password',
    outcome: 'Failure',
    processName: 'sshd[19409]',
    rawLog: 'Oct  1 03:08:27 auth-sso-01 sshd[19409]: Failed password for admin_akhtar from 185.220.101.44 port 48219 ssh2',
    normalizedSummary: 'SSH password authentication failed for user admin_akhtar from Tor node 185.220.101.44 (Attempt 3/5)',
    assetCriticality: 'Tier-1 Production',
    isPrivilegedAccount: true,
    groundTruthMalicious: true,
    ruleFlagged: true,
    anomalyScore: 89,
    anomalyFlagged: true,
    matchedRuleId: 'RULE-101',
  },
  {
    id: 'EVT-9004',
    timestamp: '2026-10-01T03:08:35Z',
    host: 'auth-sso-01.rakshak.internal',
    os: 'Linux',
    user: 'admin_akhtar',
    sourceIp: '185.220.101.44',
    geoCountry: 'DE (Tor Exit Node)',
    isUnusualGeo: true,
    isUnusualHour: true,
    category: 'Authentication',
    eventCode: 'sshd_failed_password',
    outcome: 'Failure',
    processName: 'sshd[19414]',
    rawLog: 'Oct  1 03:08:35 auth-sso-01 sshd[19414]: Failed password for admin_akhtar from 185.220.101.44 port 48233 ssh2',
    normalizedSummary: 'SSH password authentication failed for user admin_akhtar from Tor node 185.220.101.44 (Attempt 4/5)',
    assetCriticality: 'Tier-1 Production',
    isPrivilegedAccount: true,
    groundTruthMalicious: true,
    ruleFlagged: true,
    anomalyScore: 92,
    anomalyFlagged: true,
    matchedRuleId: 'RULE-101',
  },
  {
    id: 'EVT-9005',
    timestamp: '2026-10-01T03:09:02Z',
    host: 'auth-sso-01.rakshak.internal',
    os: 'Linux',
    user: 'admin_akhtar',
    sourceIp: '185.220.101.44',
    geoCountry: 'DE (Tor Exit Node)',
    isUnusualGeo: true,
    isUnusualHour: true,
    category: 'Authentication',
    eventCode: 'sshd_accepted_password',
    outcome: 'Success',
    processName: 'sshd[19422]',
    rawLog: 'Oct  1 03:09:02 auth-sso-01 sshd[19422]: Accepted password for admin_akhtar from 185.220.101.44 port 48290 ssh2',
    normalizedSummary: 'Successful SSH login for privileged user admin_akhtar after 4 consecutive failures from 185.220.101.44',
    assetCriticality: 'Tier-1 Production',
    isPrivilegedAccount: true,
    groundTruthMalicious: true,
    ruleFlagged: true,
    anomalyScore: 97,
    anomalyFlagged: true,
    matchedRuleId: 'RULE-102',
  },
  {
    id: 'EVT-9006',
    timestamp: '2026-10-01T03:12:40Z',
    host: 'prd-db-01.rakshak.internal',
    os: 'Linux',
    user: 'admin_akhtar',
    sourceIp: '10.10.15.20',
    geoCountry: 'INTERNAL-LATERAL',
    isUnusualGeo: false,
    isUnusualHour: true,
    category: 'PrivilegeChange',
    eventCode: 'sudo_root_shell',
    outcome: 'Elevated',
    processName: 'sudo[8821]',
    rawLog: 'Oct  1 03:12:40 prd-db-01 sudo[8821]: admin_akhtar : TTY=pts/1 ; PWD=/var/lib/postgresql ; USER=root ; COMMAND=/bin/bash -c "cat /etc/shadow && pg_dumpall > /tmp/.sys_cache.sql"',
    normalizedSummary: 'Privileged sudo execution to root on Crown-Jewel DB dumping credentials and PostgreSQL schema',
    assetCriticality: 'Tier-0 Crown Jewel',
    isPrivilegedAccount: true,
    groundTruthMalicious: true,
    ruleFlagged: true,
    anomalyScore: 99,
    anomalyFlagged: true,
    matchedRuleId: 'RULE-104',
  },
  {
    id: 'EVT-9007',
    timestamp: '2026-10-01T03:15:11Z',
    host: 'prd-db-01.rakshak.internal',
    os: 'Linux',
    user: 'root',
    sourceIp: '185.220.101.44',
    geoCountry: 'DE (Tor Exit Node)',
    isUnusualGeo: true,
    isUnusualHour: true,
    category: 'NetworkExfiltration',
    eventCode: 'curl_outbound_exfil',
    outcome: 'Observed',
    processName: 'curl[8904]',
    rawLog: 'Oct  1 03:15:11 prd-db-01 kernel: [UFW AUDIT] OUT=eth0 SRC=10.10.20.11 DST=185.220.101.44 PROTO=TCP DPT=8443 LEN=48920412',
    normalizedSummary: 'Outbound encrypted transfer (48.9 MB) from prd-db-01 to external C2 node 185.220.101.44:8443',
    assetCriticality: 'Tier-0 Crown Jewel',
    isPrivilegedAccount: true,
    groundTruthMalicious: true,
    ruleFlagged: true,
    anomalyScore: 96,
    anomalyFlagged: true,
    matchedRuleId: 'RULE-105',
  },

  // --- ATTACK CHAIN 2: Windows Domain Controller Spray & Privilege Escalation ---
  {
    id: 'EVT-9008',
    timestamp: '2026-10-01T04:21:05Z',
    host: 'dc-win-01.rakshak.internal',
    os: 'Windows',
    user: 'svc-backup',
    sourceIp: '91.214.124.88',
    geoCountry: 'RU (Bulletproof ASN)',
    isUnusualGeo: true,
    isUnusualHour: true,
    category: 'Authentication',
    eventCode: 'EventID_4625',
    outcome: 'Failure',
    processName: 'lsass.exe',
    rawLog: 'WinEventLog: Security: AUDIT_FAILURE(4625): An account failed to log on. Subject: svc-backup, Logon Type: 10 (RemoteInteractive), Source Network Address: 91.214.124.88, Failure Reason: Unknown user name or bad password.',
    normalizedSummary: 'Windows Event 4625: Failed RDP logon for privileged service account svc-backup from 91.214.124.88',
    assetCriticality: 'Tier-0 Crown Jewel',
    isPrivilegedAccount: true,
    groundTruthMalicious: true,
    ruleFlagged: true,
    anomalyScore: 88,
    anomalyFlagged: true,
    matchedRuleId: 'RULE-101',
  },
  {
    id: 'EVT-9009',
    timestamp: '2026-10-01T04:22:14Z',
    host: 'dc-win-01.rakshak.internal',
    os: 'Windows',
    user: 'svc-backup',
    sourceIp: '91.214.124.88',
    geoCountry: 'RU (Bulletproof ASN)',
    isUnusualGeo: true,
    isUnusualHour: true,
    category: 'Authentication',
    eventCode: 'EventID_4624',
    outcome: 'Success',
    processName: 'lsass.exe',
    rawLog: 'WinEventLog: Security: AUDIT_SUCCESS(4624): An account was successfully logged on. TargetUserName: svc-backup, LogonType: 10, IpAddress: 91.214.124.88, AuthenticationPackageName: Negotiate.',
    normalizedSummary: 'Windows Event 4624: Interactive RDP logon succeeded for service account svc-backup from 91.214.124.88',
    assetCriticality: 'Tier-0 Crown Jewel',
    isPrivilegedAccount: true,
    groundTruthMalicious: true,
    ruleFlagged: true,
    anomalyScore: 95,
    anomalyFlagged: true,
    matchedRuleId: 'RULE-102',
  },
  {
    id: 'EVT-9010',
    timestamp: '2026-10-01T04:22:16Z',
    host: 'dc-win-01.rakshak.internal',
    os: 'Windows',
    user: 'svc-backup',
    sourceIp: '91.214.124.88',
    geoCountry: 'RU (Bulletproof ASN)',
    isUnusualGeo: true,
    isUnusualHour: true,
    category: 'PrivilegeChange',
    eventCode: 'EventID_4672',
    outcome: 'Elevated',
    processName: 'lsass.exe',
    rawLog: 'WinEventLog: Security: AUDIT_SUCCESS(4672): Special privileges assigned to new logon. Account Name: svc-backup, Privileges: SeDebugPrivilege, SeBackupPrivilege, SeTakeOwnershipPrivilege.',
    normalizedSummary: 'Windows Event 4672: SeDebugPrivilege and SeTakeOwnershipPrivilege assigned to svc-backup on Domain Controller',
    assetCriticality: 'Tier-0 Crown Jewel',
    isPrivilegedAccount: true,
    groundTruthMalicious: true,
    ruleFlagged: true,
    anomalyScore: 94,
    anomalyFlagged: true,
    matchedRuleId: 'RULE-104',
  },
  {
    id: 'EVT-9011',
    timestamp: '2026-10-01T04:24:50Z',
    host: 'dc-win-01.rakshak.internal',
    os: 'Windows',
    user: 'svc-backup',
    sourceIp: '91.214.124.88',
    geoCountry: 'RU (Bulletproof ASN)',
    isUnusualGeo: true,
    isUnusualHour: true,
    category: 'AccountManagement',
    eventCode: 'EventID_4720',
    outcome: 'Elevated',
    processName: 'net1.exe',
    rawLog: 'WinEventLog: Security: AUDIT_SUCCESS(4720): A user account was created. SubjectAccountName: svc-backup, NewAccountName: support_adm$, GroupMembership: Domain Admins.',
    normalizedSummary: 'Windows Event 4720: Stealth persistence account support_adm$ created and added to Domain Admins',
    assetCriticality: 'Tier-0 Crown Jewel',
    isPrivilegedAccount: true,
    groundTruthMalicious: true,
    ruleFlagged: true,
    anomalyScore: 98,
    anomalyFlagged: true,
    matchedRuleId: 'RULE-104',
  },

  // --- STEALTH INSIDER / LOW-AND-SLOW UEBA ANOMALY (Caught by UEBA Anomaly Model, Missed by Static Brute-Force Rules) ---
  {
    id: 'EVT-9012',
    timestamp: '2026-10-01T06:10:04Z',
    host: 'fin-wks-14.rakshak.internal',
    os: 'Windows',
    user: 'm_chen',
    sourceIp: '45.155.205.19',
    geoCountry: 'SG (Unfamiliar Proxy)',
    isUnusualGeo: true,
    isUnusualHour: false,
    category: 'ProcessExecution',
    eventCode: 'EventID_4688',
    outcome: 'Observed',
    processName: 'powershell.exe',
    rawLog: 'WinEventLog: Security: AUDIT_SUCCESS(4688): A new process has been created. Creator: m_chen, CommandLine: powershell.exe -NoP -NonI -W Hidden -Enc SQBFAFgAIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACkA',
    normalizedSummary: 'Stealth Base64-encoded PowerShell execution by standard user m_chen during normal hours (Zero prior auth failures)',
    assetCriticality: 'Tier-2 Standard',
    isPrivilegedAccount: false,
    groundTruthMalicious: true,
    ruleFlagged: false, // Demonstrates where UEBA Anomaly Detection outperforms static auth/privilege rules!
    anomalyScore: 91,
    anomalyFlagged: true,
  },

  // --- BENIGN FALSE POSITIVE FOR STATIC RULE (Developer VPN Passphrase Typo) ---
  {
    id: 'EVT-9013',
    timestamp: '2026-10-01T06:45:12Z',
    host: 'k8s-ingress-02.rakshak.internal',
    os: 'Linux',
    user: 'dev_kpatel',
    sourceIp: '10.24.8.112',
    geoCountry: 'IN (Corporate VPN)',
    isUnusualGeo: false,
    isUnusualHour: false,
    category: 'Authentication',
    eventCode: 'sshd_failed_password',
    outcome: 'Failure',
    processName: 'sshd[24101]',
    rawLog: 'Oct  1 06:45:12 k8s-ingress-02 sshd[24101]: message repeated 4 times: [ Failed password for dev_kpatel from 10.24.8.112 port 55102 ssh2 ]',
    normalizedSummary: '4 rapid SSH failures from known corporate VPN IP 10.24.8.112 due to expired SSH agent key rotation',
    assetCriticality: 'Tier-1 Production',
    isPrivilegedAccount: false,
    groundTruthMalicious: false,
    ruleFlagged: true, // Static rule flags >=4 failures, whereas UEBA recognizes trusted VPN + normal dev hours
    anomalyScore: 28,
    anomalyFlagged: false,
    matchedRuleId: 'RULE-101',
  },

  // --- BENIGN BASELINE EVENTS (True Negatives) ---
  {
    id: 'EVT-9014',
    timestamp: '2026-10-01T06:50:00Z',
    host: 'prd-db-01.rakshak.internal',
    os: 'Linux',
    user: 'postgres',
    sourceIp: '127.0.0.1',
    geoCountry: 'LOCALHOST',
    isUnusualGeo: false,
    isUnusualHour: false,
    category: 'Authentication',
    eventCode: 'pam_unix_cron',
    outcome: 'Success',
    processName: 'CRON[9102]',
    rawLog: 'Oct  1 06:50:00 prd-db-01 CRON[9102]: pam_unix(cron:session): session opened for user postgres(uid=108) by (uid=0)',
    normalizedSummary: 'Scheduled hourly PostgreSQL maintenance cron session opened for user postgres',
    assetCriticality: 'Tier-0 Crown Jewel',
    isPrivilegedAccount: true,
    groundTruthMalicious: false,
    ruleFlagged: false,
    anomalyScore: 8,
    anomalyFlagged: false,
  },
  {
    id: 'EVT-9015',
    timestamp: '2026-10-01T07:02:18Z',
    host: 'dc-win-01.rakshak.internal',
    os: 'Windows',
    user: 'Administrator',
    sourceIp: '10.10.10.12',
    geoCountry: 'INTERNAL-SOC',
    isUnusualGeo: false,
    isUnusualHour: false,
    category: 'Authentication',
    eventCode: 'EventID_4624',
    outcome: 'Success',
    processName: 'lsass.exe',
    rawLog: 'WinEventLog: Security: AUDIT_SUCCESS(4624): An account was successfully logged on. TargetUserName: Administrator, LogonType: 3 (Network), IpAddress: 10.10.10.12.',
    normalizedSummary: 'Routine Kerberos network logon from internal PAW jumpbox 10.10.10.12',
    assetCriticality: 'Tier-0 Crown Jewel',
    isPrivilegedAccount: true,
    groundTruthMalicious: false,
    ruleFlagged: false,
    anomalyScore: 14,
    anomalyFlagged: false,
  },
  {
    id: 'EVT-9016',
    timestamp: '2026-10-01T07:10:44Z',
    host: 'k8s-ingress-02.rakshak.internal',
    os: 'Linux',
    user: 'kube-admin',
    sourceIp: '10.10.30.10',
    geoCountry: 'INTERNAL-K8S',
    isUnusualGeo: false,
    isUnusualHour: false,
    category: 'Authentication',
    eventCode: 'sshd_accepted_publickey',
    outcome: 'Success',
    processName: 'sshd[24880]',
    rawLog: 'Oct  1 07:10:44 k8s-ingress-02 sshd[24880]: Accepted publickey for kube-admin from 10.10.30.10 port 39104 ssh2: ED25519 SHA256:k9xL2mP4qR8',
    normalizedSummary: 'Valid ED25519 SSH public key authentication for kube-admin from control plane node',
    assetCriticality: 'Tier-1 Production',
    isPrivilegedAccount: true,
    groundTruthMalicious: false,
    ruleFlagged: false,
    anomalyScore: 11,
    anomalyFlagged: false,
  },
];

export const INITIAL_ALERTS: SecurityAlert[] = [
  {
    id: 'ALT-401',
    ruleId: 'RULE-102',
    ruleName: 'Successful Login Following Multiple Failures (Credential Compromise)',
    title: 'SSH Brute-Force Succeeded for Privileged User admin_akhtar',
    severity: 'Critical',
    confidence: 96,
    riskScore: 98,
    host: 'auth-sso-01.rakshak.internal',
    assetCriticality: 'Tier-1 Production',
    user: 'admin_akhtar',
    isPrivilegedAccount: true,
    sourceIp: '185.220.101.44',
    firstSeen: '2026-10-01T03:08:12Z',
    lastSeen: '2026-10-01T03:09:02Z',
    occurrenceCount: 5, // Deduplicated 4 failures + 1 success into 1 correlated alert
    deduplicationKey: 'RULE-102::185.220.101.44::auth-sso-01.rakshak.internal::admin_akhtar',
    triggeringEventIds: ['EVT-9001', 'EVT-9002', 'EVT-9003', 'EVT-9004', 'EVT-9005'],
    mitreTactic: 'Initial Access',
    mitreTechniqueId: 'T1078',
    mitreTechniqueName: 'Valid Accounts (Post-Brute Force)',
    mitreUrl: 'https://attack.mitre.org/techniques/T1078/',
    attackStage: 'Reconnaissance & Initial Access',
    xaiReasoning: {
      ruleTriggerExplanation: '4 consecutive sshd_failed_password events (EVT-9001..EVT-9004) were followed 27 seconds later by sshd_accepted_password (EVT-9005) from identical source IP 185.220.101.44.',
      uebaDeviationSummary: 'User admin_akhtar normally authenticates between 09:00–18:00 IST via ED25519 key from 10.24.0.0/16. Password login at 03:09 UTC from a German Tor exit node represents a 4.8σ behavioral anomaly.',
      assetRiskContext: 'Target host auth-sso-01 is a Tier-1 Identity Provider with lateral SSH trust to Crown-Jewel database prd-db-01.',
      confidenceBreakdown: [
        { factor: 'Sequential Failure-to-Success Pattern', weight: '+40%' },
        { factor: 'Verified Tor Exit Node IoC Match (185.220.101.44)', weight: '+25%' },
        { factor: 'UEBA Time & Geo Z-Score (4.8σ)', weight: '+20%' },
        { factor: 'Privileged Account Target (admin_akhtar)', weight: '+11%' },
      ],
    },
    status: 'Grouped in Incident',
    incidentId: 'INC-2026-089',
  },
  {
    id: 'ALT-402',
    ruleId: 'RULE-104',
    ruleName: 'Suspicious Privilege Escalation or Admin Group Modification',
    title: 'Root Sudo Escalation & Database Credential Dump on Crown-Jewel DB',
    severity: 'Critical',
    confidence: 98,
    riskScore: 100,
    host: 'prd-db-01.rakshak.internal',
    assetCriticality: 'Tier-0 Crown Jewel',
    user: 'admin_akhtar',
    isPrivilegedAccount: true,
    sourceIp: '10.10.15.20',
    firstSeen: '2026-10-01T03:12:40Z',
    lastSeen: '2026-10-01T03:15:11Z',
    occurrenceCount: 2,
    deduplicationKey: 'RULE-104::10.10.15.20::prd-db-01.rakshak.internal::admin_akhtar',
    triggeringEventIds: ['EVT-9006', 'EVT-9007'],
    mitreTactic: 'Privilege Escalation',
    mitreTechniqueId: 'T1548.003',
    mitreTechniqueName: 'Abuse Elevation Control Mechanism: Sudo and Sudo Caching',
    mitreUrl: 'https://attack.mitre.org/techniques/T1548/003/',
    attackStage: 'Privilege Escalation',
    xaiReasoning: {
      ruleTriggerExplanation: 'Interactive sudo command spawned /bin/bash as root reading /etc/shadow and invoking pg_dumpall (EVT-9006), followed by 48.9 MB outbound transfer over non-standard port 8443 (EVT-9007).',
      uebaDeviationSummary: 'Account admin_akhtar has 0 historical executions of pg_dumpall or /etc/shadow reads in the past 90 days (5.4σ deviation).',
      assetRiskContext: 'Host prd-db-01 is a Tier-0 Crown Jewel asset (2.0x risk multiplier) storing production customer records.',
      confidenceBreakdown: [
        { factor: 'Direct /etc/shadow & pg_dumpall Command Signature', weight: '+45%' },
        { factor: 'Correlated Prior SSO Compromise (ALT-401)', weight: '+25%' },
        { factor: '48.9 MB Anomalous Egress to 185.220.101.44', weight: '+18%' },
        { factor: 'Tier-0 Asset Criticality Multiplier', weight: '+10%' },
      ],
    },
    status: 'Grouped in Incident',
    incidentId: 'INC-2026-089',
  },
  {
    id: 'ALT-403',
    ruleId: 'RULE-104',
    ruleName: 'Suspicious Privilege Escalation or Admin Group Modification',
    title: 'Windows Domain Controller RDP Compromise & Backdoor Admin Creation',
    severity: 'Critical',
    confidence: 95,
    riskScore: 99,
    host: 'dc-win-01.rakshak.internal',
    assetCriticality: 'Tier-0 Crown Jewel',
    user: 'svc-backup',
    isPrivilegedAccount: true,
    sourceIp: '91.214.124.88',
    firstSeen: '2026-10-01T04:21:05Z',
    lastSeen: '2026-10-01T04:24:50Z',
    occurrenceCount: 4,
    deduplicationKey: 'RULE-104::91.214.124.88::dc-win-01.rakshak.internal::svc-backup',
    triggeringEventIds: ['EVT-9008', 'EVT-9009', 'EVT-9010', 'EVT-9011'],
    mitreTactic: 'Persistence',
    mitreTechniqueId: 'T1098',
    mitreTechniqueName: 'Account Manipulation (Domain Admins)',
    mitreUrl: 'https://attack.mitre.org/techniques/T1098/',
    attackStage: 'Privilege Escalation',
    xaiReasoning: {
      ruleTriggerExplanation: 'Service account svc-backup authenticated via interactive RDP LogonType 10 (EVT-9009) after failure (EVT-9008), received SeDebugPrivilege (EVT-9010), and created hidden account support_adm$ in Domain Admins (EVT-9011).',
      uebaDeviationSummary: 'Service account svc-backup is restricted to non-interactive LogonType 4 (Batch). Interactive RDP LogonType 10 from external Russian ASN 91.214.124.88 violates service account policy (5.1σ).',
      assetRiskContext: 'dc-win-01 is the Primary Active Directory Domain Controller (Tier-0 Crown Jewel).',
      confidenceBreakdown: [
        { factor: 'EventID 4720 Backdoor Account with $ Suffix', weight: '+42%' },
        { factor: 'Service Account Interactive RDP Violation', weight: '+28%' },
        { factor: 'EventID 4672 SeDebugPrivilege Assignment', weight: '+15%' },
        { factor: 'External Bulletproof Hosting IP (91.214.124.88)', weight: '+10%' },
      ],
    },
    status: 'Grouped in Incident',
    incidentId: 'INC-2026-090',
  },
  {
    id: 'ALT-404',
    ruleId: 'RULE-103',
    ruleName: 'Off-Hours or Unfamiliar Geolocation Authentication',
    title: 'UEBA Anomaly: Obfuscated PowerShell Execution from Unfamiliar Proxy',
    severity: 'High',
    confidence: 88,
    riskScore: 84,
    host: 'fin-wks-14.rakshak.internal',
    assetCriticality: 'Tier-2 Standard',
    user: 'm_chen',
    isPrivilegedAccount: false,
    sourceIp: '45.155.205.19',
    firstSeen: '2026-10-01T06:10:04Z',
    lastSeen: '2026-10-01T06:10:04Z',
    occurrenceCount: 1,
    deduplicationKey: 'UEBA-4688::45.155.205.19::fin-wks-14.rakshak.internal::m_chen',
    triggeringEventIds: ['EVT-9012'],
    mitreTactic: 'Execution',
    mitreTechniqueId: 'T1059.001',
    mitreTechniqueName: 'Command and Scripting Interpreter: PowerShell',
    mitreUrl: 'https://attack.mitre.org/techniques/T1059/001/',
    attackStage: 'Lateral Movement',
    xaiReasoning: {
      ruleTriggerExplanation: 'Flagged by UEBA Statistical Behavioral Engine (Anomaly Score: 91/100) on Windows EventID 4688 containing -Enc Base64 WebClient download cradle.',
      uebaDeviationSummary: 'Finance analyst m_chen has never executed powershell.exe with encoded parameters in 180 days of baseline telemetry (4.4σ anomaly).',
      assetRiskContext: 'Workstation fin-wks-14 has access to ERP treasury shares.',
      confidenceBreakdown: [
        { factor: 'UEBA Process Peer-Group Deviation (4.4σ)', weight: '+45%' },
        { factor: 'Base64 IEX WebClient Download Cradle Pattern', weight: '+33%' },
        { factor: 'Unverified Suspicious Proxy IP (45.155.205.19)', weight: '+10%' },
      ],
    },
    status: 'Open',
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'INC-2026-089',
    title: 'Multi-Stage SSH Compromise, Sudo Escalation & PostgreSQL Exfiltration',
    status: 'Investigating',
    severity: 'Critical',
    confidence: 97,
    assignee: 'A. Sharma (Tier-3 Threat Hunt Lead)',
    createdAt: '2026-10-01T03:15:30Z',
    updatedAt: '2026-10-01T07:05:00Z',
    alertIds: ['ALT-401', 'ALT-402'],
    eventIds: ['EVT-9001', 'EVT-9002', 'EVT-9003', 'EVT-9004', 'EVT-9005', 'EVT-9006', 'EVT-9007'],
    affectedHosts: ['auth-sso-01.rakshak.internal', 'prd-db-01.rakshak.internal'],
    affectedUsers: ['admin_akhtar', 'root'],
    sourceIps: ['185.220.101.44', '10.10.15.20'],
    mitreTechniques: ['T1110.001', 'T1078', 'T1548.003', 'T1048'],
    notes: [
      {
        id: 'N-101',
        author: 'Rakshak Correlation Engine',
        timestamp: '2026-10-01T03:15:32Z',
        content: 'Automatically deduplicated 5 SSH authentication events on auth-sso-01 and linked lateral movement to prd-db-01 via shared actor admin_akhtar.',
        evidenceRef: 'EVT-9005 -> EVT-9006',
      },
      {
        id: 'N-102',
        author: 'A. Sharma (Tier-3 Threat Hunt Lead)',
        timestamp: '2026-10-01T03:24:10Z',
        content: 'Confirmed 185.220.101.44 is a known Tor exit node. Staging artifact /tmp/.sys_cache.sql was created prior to 48.9 MB outbound TCP transfer on port 8443. Playbook approval requested to block IP and lock admin_akhtar.',
        evidenceRef: 'EVT-9007',
      },
    ],
    auditTrail: [
      {
        id: 'AUD-1',
        timestamp: '2026-10-01T03:15:30Z',
        actor: 'Rakshak Auto-Correlator',
        action: 'INCIDENT_CREATED',
        details: 'Created Critical Incident INC-2026-089 from deduplicated alerts ALT-401 and ALT-402.',
      },
      {
        id: 'AUD-2',
        timestamp: '2026-10-01T03:18:05Z',
        actor: 'A. Sharma (Tier-3 Threat Hunt Lead)',
        action: 'STATUS_CHANGED',
        details: 'Status transitioned from New to Investigating; assigned to A. Sharma.',
      },
      {
        id: 'AUD-3',
        timestamp: '2026-10-01T03:25:00Z',
        actor: 'Rakshak SOAR Engine',
        action: 'PLAYBOOK_QUEUED',
        details: 'Queued PB-01 (Perimeter Block 185.220.101.44) & PB-02 (Disable Account admin_akhtar) awaiting analyst approval.',
      },
    ],
    aiReport: {
      generatedAt: '2026-10-01T03:20:00Z',
      modelUsed: 'gemini-3.8-flash (Rakshak XAI Engine)',
      plainEnglishSummary:
        'An external threat actor operating from Tor exit node 185.220.101.44 conducted a targeted SSH password-guessing attack against the identity gateway (auth-sso-01), compromising the privileged account "admin_akhtar" after four failed attempts. Within three minutes of initial access, the attacker pivoted internally to the Crown-Jewel production database server (prd-db-01), abused sudo privileges to read /etc/shadow and dump the PostgreSQL database to /tmp/.sys_cache.sql, and exfiltrated 48.9 MB of data back to 185.220.101.44 over TCP port 8443.',
      triggeringEventsExplanation: [
        {
          eventId: 'EVT-9001..EVT-9004',
          timestamp: '2026-10-01T03:08:12Z - 03:08:35Z',
          whatHappened: 'Four rapid SSH password failures for user admin_akhtar from 185.220.101.44.',
          whySuspicious: 'Indicates automated credential stuffing/brute force from an external anonymization network during off-hours (03:08 UTC).',
        },
        {
          eventId: 'EVT-9005',
          timestamp: '2026-10-01T03:09:02Z',
          whatHappened: 'SSH password accepted for admin_akhtar from 185.220.101.44.',
          whySuspicious: 'Successful login immediately following consecutive failures confirms credential compromise (MITRE T1078).',
        },
        {
          eventId: 'EVT-9006',
          timestamp: '2026-10-01T03:12:40Z',
          whatHappened: 'User admin_akhtar executed sudo /bin/bash on prd-db-01 to cat /etc/shadow and run pg_dumpall.',
          whySuspicious: 'High-severity privilege escalation (T1548.003) and credential/database harvesting on a Tier-0 Crown Jewel asset.',
        },
        {
          eventId: 'EVT-9007',
          timestamp: '2026-10-01T03:15:11Z',
          whatHappened: 'Outbound TCP connection from prd-db-01 to 185.220.101.44:8443 transferring 48,920,412 bytes.',
          whySuspicious: 'Matches the size and timing of the staged /tmp/.sys_cache.sql dump, indicating active data exfiltration (T1048).',
        },
      ],
      chronologicalTimeline: [
        {
          step: 1,
          timestamp: '03:08:12 UTC',
          stage: 'Credential Access (T1110.001)',
          asset: 'auth-sso-01.rakshak.internal',
          actorOrIp: '185.220.101.44',
          description: 'SSH password guessing burst initiated against admin_akhtar (4 failed attempts in 23s).',
        },
        {
          step: 2,
          timestamp: '03:09:02 UTC',
          stage: 'Initial Access (T1078)',
          asset: 'auth-sso-01.rakshak.internal',
          actorOrIp: 'admin_akhtar (185.220.101.44)',
          description: 'Valid password guessed; interactive SSH session established.',
        },
        {
          step: 3,
          timestamp: '03:12:40 UTC',
          stage: 'Privilege Escalation (T1548.003)',
          asset: 'prd-db-01.rakshak.internal',
          actorOrIp: 'admin_akhtar -> root',
          description: 'Lateral SSH pivot from 10.10.15.20 to prd-db-01; sudo used to dump /etc/shadow and PostgreSQL tables.',
        },
        {
          step: 4,
          timestamp: '03:15:11 UTC',
          stage: 'Exfiltration (T1048)',
          asset: 'prd-db-01.rakshak.internal',
          actorOrIp: 'root -> 185.220.101.44:8443',
          description: '48.9 MB outbound transfer over TCP/8443 to external Tor node.',
        },
      ],
      affectedAssetsAndScope: [
        {
          asset: 'prd-db-01.rakshak.internal (10.10.20.11)',
          criticality: 'Tier-0 Crown Jewel (2.0x Risk Weight)',
          impactSummary: 'Root compromise, OS password hashes (/etc/shadow) read, and full PostgreSQL database dump staged and exfiltrated.',
        },
        {
          asset: 'auth-sso-01.rakshak.internal (10.10.15.20)',
          criticality: 'Tier-1 Production (1.5x Risk Weight)',
          impactSummary: 'Initial entry vector via SSH password authentication; used as lateral pivot host.',
        },
      ],
      suggestedInvestigationSteps: [
        'Approve SOAR Playbooks PB-01 and PB-02 immediately to block 185.220.101.44 at the perimeter firewall and lock account admin_akhtar.',
        'Inspect /tmp/.sys_cache.sql on prd-db-01 and compute its SHA-256 hash to verify exact tables included in the 48.9 MB transfer.',
        'Rotate all local Linux password hashes on prd-db-01 and revoke active SSH authorized_keys for root and admin_akhtar.',
        'Disable PasswordAuthentication in /etc/ssh/sshd_config on auth-sso-01 to enforce hardware-backed ED25519 keys.',
      ],
      explainableAiReasoning:
        'Confidence is rated at 97% because deterministic sequence correlation (RULE-102 + RULE-104 + RULE-105) aligns with a 5.4σ UEBA statistical deviation and a Verified Threat Intelligence match on 185.220.101.44.',
      limitationsAndUncertainties: [
        'Encrypted Payload Visibility: Telemetry confirms 48.9 MB exited over TCP/8443 (EVT-9007), but without TLS inspection or full PCAP capture, exact row-level contents of the transmitted stream are inferred from the preceding pg_dumpall command (EVT-9006).',
        'Credential Reuse Scope: Logs show local /etc/shadow access on prd-db-01, but offline cracking success by the adversary cannot be measured from host logs alone.',
        'Tor Exit Node Attribution: Source IP 185.220.101.44 is a public Tor exit relay; IP-level blocking prevents immediate session resumption but does not attribute the upstream threat actor identity.',
      ],
    },
  },
  {
    id: 'INC-2026-090',
    title: 'Active Directory Domain Controller RDP Compromise & Backdoor Admin Creation',
    status: 'New',
    severity: 'Critical',
    confidence: 95,
    assignee: 'M. Vance (Incident Response Lead)',
    createdAt: '2026-10-01T04:25:10Z',
    updatedAt: '2026-10-01T04:25:10Z',
    alertIds: ['ALT-403'],
    eventIds: ['EVT-9008', 'EVT-9009', 'EVT-9010', 'EVT-9011'],
    affectedHosts: ['dc-win-01.rakshak.internal'],
    affectedUsers: ['svc-backup', 'support_adm$'],
    sourceIps: ['91.214.124.88'],
    mitreTechniques: ['T1110.001', 'T1078', 'T1134', 'T1098'],
    notes: [
      {
        id: 'N-201',
        author: 'Rakshak Correlation Engine',
        timestamp: '2026-10-01T04:25:12Z',
        content: 'Correlated Windows Security EventIDs 4625 -> 4624 (LogonType 10) -> 4672 -> 4720 on Primary Domain Controller dc-win-01.',
        evidenceRef: 'EVT-9011',
      },
    ],
    auditTrail: [
      {
        id: 'AUD-201',
        timestamp: '2026-10-01T04:25:10Z',
        actor: 'Rakshak Auto-Correlator',
        action: 'INCIDENT_CREATED',
        details: 'Created Critical Incident INC-2026-090 from Windows Domain Controller alert ALT-403.',
      },
    ],
  },
];

export const INITIAL_IOC_DATABASE: IoCRecord[] = [
  {
    id: 'IOC-01',
    indicator: '185.220.101.44',
    type: 'IPv4',
    reputation: 'Malicious',
    confidenceScore: 98,
    verificationStatus: 'Verified Intelligence',
    source: 'AbuseIPDB + AlienVault OTX (Multi-Source Confirmed)',
    retrievedAt: '2026-10-01T07:12:04Z',
    cacheStatus: 'CACHE_HIT',
    asnOrRegistrar: 'AS60729 Zwiebelfreunde e.V. (Tor Exit Node)',
    country: 'Germany (DE)',
    threatActorOrCampaign: 'Credential Stuffing & Automated SSH Scanner Cluster',
    associatedMalware: 'SSH-Brute / Custom Exfil Listener',
    sightingsCount: 7,
    summary: 'Verified Tor exit relay actively cited in 1,420+ abuse reports in the last 24h for SSH brute-force and post-exploitation C2 tunneling.',
  },
  {
    id: 'IOC-02',
    indicator: '91.214.124.88',
    type: 'IPv4',
    reputation: 'Malicious',
    confidenceScore: 94,
    verificationStatus: 'Verified Intelligence',
    source: 'VirusTotal Enterprise + AbuseIPDB',
    retrievedAt: '2026-10-01T07:14:22Z',
    cacheStatus: 'CACHE_HIT',
    asnOrRegistrar: 'AS49505 Selectel / Bulletproof VPS Transit',
    country: 'Russian Federation (RU)',
    threatActorOrCampaign: 'FIN-Shadow / RDP Initial Access Broker',
    associatedMalware: 'Cobalt Strike / AD Persistence Toolkit',
    sightingsCount: 4,
    summary: 'Verified malicious infrastructure targeting exposed RDP and Active Directory service accounts across enterprise networks.',
  },
  {
    id: 'IOC-03',
    indicator: '45.155.205.19',
    type: 'IPv4',
    reputation: 'Suspicious',
    confidenceScore: 64,
    verificationStatus: 'Unverified Observation',
    source: 'Rakshak Local Telemetry Heuristic (Single-Sighting)',
    retrievedAt: '2026-10-01T07:15:50Z',
    cacheStatus: 'LIVE_FETCH',
    asnOrRegistrar: 'AS209605 HostRoyale Cloud',
    country: 'Singapore (SG)',
    threatActorOrCampaign: 'Unattributed / Under Investigation',
    associatedMalware: 'Encoded PowerShell Stager (Suspected)',
    sightingsCount: 1,
    summary: 'Unverified observation: IP has no prior external blacklist consensus, but was observed in local UEBA anomaly EVT-9012.',
  },
  {
    id: 'IOC-04',
    indicator: 'cdn-telemetry-sync.top',
    type: 'Domain',
    reputation: 'Malicious',
    confidenceScore: 92,
    verificationStatus: 'Verified Intelligence',
    source: 'URLhaus + ThreatFox Feed',
    retrievedAt: '2026-10-01T06:58:10Z',
    cacheStatus: 'CACHE_HIT',
    asnOrRegistrar: 'NameSilo LLC (Newly Registered Domain < 7d)',
    country: 'Panama (PA)',
    threatActorOrCampaign: 'LummaStealer / PowerShell Dropper C2',
    associatedMalware: 'PowerShell WebClient Stage-2 Loader',
    sightingsCount: 2,
    summary: 'Verified command-and-control domain decoded from the Base64 PowerShell command in EVT-9012.',
  },
  {
    id: 'IOC-05',
    indicator: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    type: 'SHA-256',
    reputation: 'Suspicious',
    confidenceScore: 71,
    verificationStatus: 'Unverified Observation',
    source: 'Rakshak Endpoint FIM Sensor',
    retrievedAt: '2026-10-01T07:01:00Z',
    cacheStatus: 'CACHE_HIT',
    asnOrRegistrar: 'ELF 64-bit LSB pie executable (Stripped)',
    country: 'Local Artifact',
    threatActorOrCampaign: 'Unknown Local Binary',
    associatedMalware: 'Heuristic Packing Detected',
    sightingsCount: 1,
    summary: 'Unverified file hash observed in /tmp; not yet indexed in public VirusTotal corpus.',
  },
];

export const INITIAL_PLAYBOOKS: PlaybookAction[] = [
  {
    id: 'PB-01',
    incidentId: 'INC-2026-089',
    playbookName: 'SOAR-NET-01: Perimeter & Host Firewall IP Block',
    actionType: 'Block Firewall IP',
    targetEntity: '185.220.101.44 (Tor Exit & Exfil Destination)',
    recommendedReason: 'Active data exfiltration (48.9 MB) and SSH compromise originating from 185.220.101.44.',
    requiresApproval: true,
    approvalStatus: 'Pending Analyst Approval',
    requestedAt: '2026-10-01T03:25:00Z',
  },
  {
    id: 'PB-02',
    incidentId: 'INC-2026-089',
    playbookName: 'SOAR-IAM-04: Disable Compromised Privileged Account',
    actionType: 'Disable User Account',
    targetEntity: 'admin_akhtar (Linux PAM & SSO Directory)',
    recommendedReason: 'Account credentials compromised via brute force and abused for root sudo escalation on prd-db-01.',
    requiresApproval: true,
    approvalStatus: 'Pending Analyst Approval',
    requestedAt: '2026-10-01T03:25:05Z',
  },
  {
    id: 'PB-03',
    incidentId: 'INC-2026-090',
    playbookName: 'SOAR-AD-09: Disable Rogue Domain Admin & Revoke Kerberos TGTs',
    actionType: 'Disable User Account',
    targetEntity: 'support_adm$ & svc-backup (Active Directory)',
    recommendedReason: 'Unauthorized backdoor account support_adm$ created by svc-backup during anomalous RDP session from 91.214.124.88.',
    requiresApproval: true,
    approvalStatus: 'Pending Analyst Approval',
    requestedAt: '2026-10-01T04:25:15Z',
  },
  {
    id: 'PB-04',
    incidentId: 'INC-2026-089',
    playbookName: 'SOAR-SOC-01: PagerDuty & CISO Escalation Dispatch',
    actionType: 'Notify SOC & Admin',
    targetEntity: 'secops-oncall@rakshak.internal',
    recommendedReason: 'Mandatory notification for Tier-0 Crown Jewel asset compromise.',
    requiresApproval: false,
    approvalStatus: 'Auto-Executed (Low Risk)',
    requestedAt: '2026-10-01T03:15:35Z',
    approvedBy: 'Rakshak Policy Auto-Rule',
    executedAt: '2026-10-01T03:15:36Z',
    outcomeLog: 'Dispatched encrypted webhook alert #9841 to SOC Tier-3 and Database Custodians.',
  },
];

export const INITIAL_UEBA_PROFILES: UEBAProfile[] = [
  {
    user: 'admin_akhtar',
    role: 'Principal Infrastructure SRE',
    isPrivileged: true,
    typicalHours: '09:00 – 18:30 UTC',
    knownHosts: ['auth-sso-01.rakshak.internal', 'k8s-ingress-02.rakshak.internal'],
    usualCountries: ['IN', 'US-VPN'],
    baselineDailyAuthFailures: 0.2,
    currentSessionAuthFailures: 4,
    baselinePrivilegeCommands: 2.1,
    currentPrivilegeCommands: 9,
    uebaRiskScore: 97,
    zScoreDeviation: 5.4,
    detectedAnomalies: [
      'Off-hours login at 03:09 UTC (Baseline: 09:00–18:30 UTC)',
      'First-seen source geolocation: Germany Tor Exit Node (185.220.101.44)',
      'First-seen execution of pg_dumpall and /etc/shadow read on prd-db-01',
    ],
  },
  {
    user: 'svc-backup',
    role: 'Automated AD Backup Service Account',
    isPrivileged: true,
    typicalHours: '01:00 – 02:00 UTC (Batch Only)',
    knownHosts: ['dc-win-01.rakshak.internal'],
    usualCountries: ['INTERNAL-SUBNET'],
    baselineDailyAuthFailures: 0.0,
    currentSessionAuthFailures: 1,
    baselinePrivilegeCommands: 1.0,
    currentPrivilegeCommands: 5,
    uebaRiskScore: 95,
    zScoreDeviation: 5.1,
    detectedAnomalies: [
      'Interactive RDP LogonType 10 used by non-human service account',
      'External source IP 91.214.124.88 (Russian ASN)',
      'Executed net1.exe user creation (EventID 4720)',
    ],
  },
  {
    user: 'm_chen',
    role: 'Senior Treasury Analyst',
    isPrivileged: false,
    typicalHours: '06:00 – 15:00 UTC',
    knownHosts: ['fin-wks-14.rakshak.internal'],
    usualCountries: ['SG', 'INTERNAL-LAN'],
    baselineDailyAuthFailures: 0.1,
    currentSessionAuthFailures: 0,
    baselinePrivilegeCommands: 0.0,
    currentPrivilegeCommands: 1,
    uebaRiskScore: 91,
    zScoreDeviation: 4.4,
    detectedAnomalies: [
      'First-time execution of powershell.exe with -EncodedCommand and Hidden window flag',
      'Peer-group deviation: 0% of Finance peers invoke encoded PowerShell scripts',
    ],
  },
  {
    user: 'dev_kpatel',
    role: 'Kubernetes Platform Developer',
    isPrivileged: false,
    typicalHours: '05:30 – 14:30 UTC',
    knownHosts: ['k8s-ingress-02.rakshak.internal'],
    usualCountries: ['IN (Corporate VPN)'],
    baselineDailyAuthFailures: 0.8,
    currentSessionAuthFailures: 4,
    baselinePrivilegeCommands: 0.5,
    currentPrivilegeCommands: 0,
    uebaRiskScore: 28,
    zScoreDeviation: 1.1,
    detectedAnomalies: [
      'Minor auth failure spike from known corporate VPN IP 10.24.8.112 (Classified Benign by UEBA)',
    ],
  },
];

export const SAMPLE_RAW_LOG_PACKETS = [
  {
    id: 'PACK-LINUX-SSH',
    label: 'Linux SSH Brute Force + Root Sudo Escalation (Syslog / auth.log)',
    osHint: 'Linux' as const,
    rawText: `Oct  1 07:18:02 prd-db-01 sshd[31004]: Failed password for root from 193.42.33.18 port 51201 ssh2
Oct  1 07:18:05 prd-db-01 sshd[31009]: Failed password for root from 193.42.33.18 port 51215 ssh2
Oct  1 07:18:09 prd-db-01 sshd[31012]: Failed password for root from 193.42.33.18 port 51229 ssh2
Oct  1 07:18:14 prd-db-01 sshd[31018]: Accepted password for root from 193.42.33.18 port 51244 ssh2
Oct  1 07:18:45 prd-db-01 sudo[31055]: root : TTY=pts/2 ; PWD=/root ; USER=root ; COMMAND=/usr/bin/usermod -aG sudo backup_op`,
  },
  {
    id: 'PACK-WIN-AD',
    label: 'Windows Event Log: Kerberos Failure + Special Privileges (Event 4625/4624/4672)',
    osHint: 'Windows' as const,
    rawText: `WinEventLog: Security: AUDIT_FAILURE(4625): An account failed to log on. Subject: Administrator, Logon Type: 10, Source Network Address: 176.111.174.29, Failure Reason: Bad password.
WinEventLog: Security: AUDIT_SUCCESS(4624): An account was successfully logged on. TargetUserName: Administrator, LogonType: 10, IpAddress: 176.111.174.29, AuthenticationPackageName: NTLM.
WinEventLog: Security: AUDIT_SUCCESS(4672): Special privileges assigned to new logon. Account Name: Administrator, Privileges: SeDebugPrivilege, SeTcbPrivilege.`,
  },
];
